export const GET_POKEMONS = "GET_POKEMONS";
export const POKEMONS_REQUEST = "POKEMONS_REQUEST";
export const POKEMONS_REQUEST_FINISHED = "POKEMONS_REQUEST_FINISHED";
export const POKEMONS_REQUEST_FAILED = "POKEMONS_REQUEST_FAILED";
export const GET_DETAILS = "GET_DETAILS";
export const REMOVE_POKEMON = "REMOVE_POKEMON";
export const GET_TYPES = "GET_TYPES";

export const FILTER_TYPE = "FILTER_TYPE";
export const SORT_ATTACK = "SORT_ATTACK";
export const SORT_NAME = "SORT_NAME";
export const FILTER_ORIGIN = "FILTER_ORIGIN";

export const RESET_FILTERS = "RESET_FILTERS";

export const SEARCH_NAME = "SEARCH_NAME";
export const SEARCH_NAME_INPUT = "SEARCH_NAME_INPUT";

export const SET_LOADING = "SET_LOADING";
export const SET_FILTER_LOADING = "SET_FILTER_LOADING";
export const SET_FILTER_REFRESH_LOADING = "SET_FILTER_REFRESH_LOADING";
